# 1.- Acceder a los datos y prepararlos para su analisis.

## Importacion de las librerias necesarias.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

## Importacion de los datos

In [2]:
visits_df = pd.read_csv('visits_log_us.csv')
orders_df = pd.read_csv('orders_log_us.csv')
costs_df = pd.read_csv('costs_us.csv')

## Primer vistazo a los DataFrames

In [3]:
#DataFrame de visitas
print(visits_df.head())
print(visits_df.info())

    Device               End Ts  Source Id             Start Ts  \
0    touch  2017-12-20 17:38:00          4  2017-12-20 17:20:00
1  desktop  2018-02-19 17:21:00          2  2018-02-19 16:53:00
2    touch  2017-07-01 01:54:00          5  2017-07-01 01:54:00
3  desktop  2018-05-20 11:23:00          9  2018-05-20 10:59:00
4  desktop  2017-12-27 14:06:00          3  2017-12-27 14:06:00

                    Uid
0  16879256277535980062
1    104060357244891740
2   7459035603376831527
3  16174680259334210214
4   9969694820036681168
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 359400 entries, 0 to 359399
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Device     359400 non-null  object
 1   End Ts     359400 non-null  object
 2   Source Id  359400 non-null  int64
 3   Start Ts   359400 non-null  object
 4   Uid        359400 non-null  uint64
dtypes: int64(1), object(3), uint64(1)
memory usage: 13.7+ MB
None

In [4]:
#Convertiremos las columnas "End Ts" y "Start Ts" a fechas
visits_df['End Ts'] = pd.to_datetime(visits_df['End Ts'])
visits_df['Start Ts'] = pd.to_datetime(visits_df['Start Ts'])
print(visits_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 359400 entries, 0 to 359399
Data columns (total 5 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Device     359400 non-null  object
 1   End Ts     359400 non-null  datetime64[ns]
 2   Source Id  359400 non-null  int64
 3   Start Ts   359400 non-null  datetime64[ns]
 4   Uid        359400 non-null  uint64
dtypes: datetime64[ns](2), int64(1), object(1), uint64(1)
memory usage: 13.7+ MB
None

In [5]:
#Buscaremnos valores duplicados en el DataFrame visits_df
visits_df[visits_df.duplicated()]

Empty DataFrame
Columns: [Device, End Ts, Source Id, Start Ts, Uid]
Index: []

In [6]:
# DataFrame de ordenes
print(orders_df.head())
print(orders_df.info())

                Buy Ts  Revenue                   Uid
0  2017-06-01 00:10:00    17.00  10329302124590727494
1  2017-06-01 00:25:00     0.55  11627257723692907447
2  2017-06-01 00:27:00     0.37  17903680561304213844
3  2017-06-01 00:29:00     0.55  16109239769442553005
4  2017-06-01 07:58:00     0.37  14200605875248379450
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50415 entries, 0 to 50414
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Buy Ts   50415 non-null  object
 1   Revenue  50415 non-null  float64
 2   Uid      50415 non-null  uint64
dtypes: float64(1), object(1), uint64(1)
memory usage: 1.2+ MB
None

In [7]:
#Se convierte la columna 'But Ts' a formato fecha
orders_df['Buy Ts'] = pd.to_datetime(orders_df['Buy Ts'])
print(orders_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50415 entries, 0 to 50414
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Buy Ts   50415 non-null  datetime64[ns]
 1   Revenue  50415 non-null  float64
 2   Uid      50415 non-null  uint64
dtypes: datetime64[ns](1), float64(1), uint64(1)
memory usage: 1.2 MB
None

In [8]:
#Buscamos filas duplicadas en el DataFrame orders_df
orders_df[orders_df.duplicated()]

Empty DataFrame
Columns: [Buy Ts, Revenue, Uid]
Index: []

In [9]:
#DataFrame de costos
print(costs_df.head())
print(costs_df.info())

   source_id          dt  costs
0          1  2017-06-01  75.20
1          1  2017-06-02  62.25
2          1  2017-06-03  36.53
3          1  2017-06-04  55.00
4          1  2017-06-05  57.08
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2542 entries, 0 to 2541
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   source_id  2542 non-null   int64
 1   dt         2542 non-null   object
 2   costs      2542 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 59.7+ KB
None

In [10]:
#Convertimos la columna 'dt' a formato de fecha
costs_df['dt'] = pd.to_datetime(costs_df['dt'])
print(costs_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2542 entries, 0 to 2541
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   source_id  2542 non-null   int64
 1   dt         2542 non-null   datetime64[ns]
 2   costs      2542 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(1)
memory usage: 59.7 KB
None

In [11]:
#Buscando duplicados en el DataFrame costs_df
costs_df[costs_df.duplicated()]

Empty DataFrame
Columns: [source_id, dt, costs]
Index: []

# 2.- Informes y calculo de métricas

## DataFrame visitas

### ¿Cuántas personas lo usan cada día, semana y mes?

In [12]:
#Calculo de visitas por día
visitors_per_day = visits_df.groupby(visits_df['Start Ts'].dt.date)['Uid'].nunique().reset_index()
visitors_per_day.columns = ['date', 'visitors']
visitors_per_day.head()

         date  visitors
0  2017-06-01       605
1  2017-06-02       608
2  2017-06-03       445
3  2017-06-04       476
4  2017-06-05       820

In [13]:
#Promedio de personas que visitan por día
visitors_per_day_mean = '{:.2f}'.format(visitors_per_day['visitors'].mean())
print('Promedio de personas que hacen visitas diarias:', visitors_per_day_mean)

Promedio de personas que hacen visitas diarias: 907.99

In [14]:
#Calculo de visitas por semana
visitors_per_week = visits_df.groupby(visits_df['Start Ts'].dt.to_period('W'))['Uid'].nunique().reset_index()
visitors_per_week.columns = ['date_week', 'visitors']
visitors_per_week.head()

               date_week  visitors
0  2017-05-29/2017-06-04      2021
1  2017-06-05/2017-06-11      4129
2  2017-06-12/2017-06-18      2812
3  2017-06-19/2017-06-25      2878
4  2017-06-26/2017-07-02      3064

In [15]:
#Promedio de visitas por semana
visitors_per_week_mean = '{:.2f}'.format(visitors_per_week['visitors'].mean())
print('Promedio personas que visitan por semana:', visitors_per_week_mean)

Promedio personas que visitan por semana: 5716.25

In [16]:
#Promedio de visitas por mes
visitors_per_month = visits_df.groupby(visits_df['Start Ts'].dt.to_period('M'))['Uid'].nunique().reset_index()
visitors_per_month.columns = ['date_month','visitors']
visitors_per_month.head()

  date_month  visitors
0    2017-06     13259
1    2017-07     14183
2    2017-08     11631
3    2017-09     18975
4    2017-10     29692

In [17]:
#Promedio de visitas por mes
visitors_per_month_mean = '{:.2f}'.format(visitors_per_month['visitors'].mean())
print('Promedio personas que visitan por mes:', visitors_per_month_mean)

Promedio personas que visitan por mes: 23228.42

### Cantidad de sesiones por día

In [18]:
visits_per_day = visits_df.groupby(visits_df['Start Ts'].dt.date)['Uid'].count().reset_index()
visits_per_day.columns = ['date', 'total_visits']
visits_per_day.head()

         date  total_visits
0  2017-06-01           664
1  2017-06-02           658
2  2017-06-03           477
3  2017-06-04           510
4  2017-06-05           893

In [19]:
#Promedio de visitas por día
visits_per_day_mean = '{:.2f}'.format(visits_per_day['total_visits'].mean())
print('Promedio de visitas diarias:', visits_per_day_mean)

Promedio de visitas diarias: 987.36

### Duracion de cada sesion

In [20]:
visits_df['session_time'] = visits_df['End Ts'] - visits_df['Start Ts']
visits_df.head()

,Device,End Ts,Source Id,Start Ts,Uid,session_time
0,touch,2017-12-20 17:38:00,4,2017-12-20 17:20:00,16879256277535980062,0 days 00:18:00
1,desktop,2018-02-19 17:21:00,2,2018-02-19 16:53:00,104060357244891740,0 days 00:28:00
2,touch,2017-07-01 01:54:00,5,2017-07-01 01:54:00,7459035603376831527,0 days 00:00:00
3,desktop,2018-05-20 11:23:00,9,2018-05-20 10:59:00,16174680259334210214,0 days 00:24:00
4,desktop,2017-12-27 14:06:00,3,2017-12-27 14:06:00,9969694820036681168,0 days 00:00:00

In [21]:
print('Tiempo promedio de la duracion de cada visita:', visits_df['session_time'].mean())

Tiempo promedio de la duracion de cada visita: 0 days 00:10:43.025687256

### Frecuencia con la cual los usuarios vuelven a hacer una visita

In [22]:
#Obtenemos el mes de la primera visita para cada user
first_visit_user = visits_df.groupby('Uid')['Start Ts'].min()
first_visit_user.name = 'first_visit_date'
first_visit_user.head()

Uid
11863502262781    2018-03-01 17:27:00
49537067089222    2018-02-06 15:55:00
297729379853735   2017-06-07 18:47:00
313578113262317   2017-09-18 22:49:00
325320750514679   2017-09-30 14:29:00
Name: first_visit_date, dtype: datetime64[ns]

In [23]:
#Añadimos esta columna del primer mes de visita al DataFrame visits_df
added_first_order_month = visits_df.join(first_visit_user, on='Uid')
added_first_order_month.head()

,Device,End Ts,Source Id,Start Ts,Uid,session_time,first_visit_date
0,touch,2017-12-20 17:38:00,4,2017-12-20 17:20:00,16879256277535980062,0 days 00:18:00,2017-12-20 17:20:00
1,desktop,2018-02-19 17:21:00,2,2018-02-19 16:53:00,104060357244891740,0 days 00:28:00,2018-02-19 16:53:00
2,touch,2017-07-01 01:54:00,5,2017-07-01 01:54:00,7459035603376831527,0 days 00:00:00,2017-07-01 01:54:00
3,desktop,2018-05-20 11:23:00,9,2018-05-20 10:59:00,16174680259334210214,0 days 00:24:00,2018-03-09 20:05:00
4,desktop,2017-12-27 14:06:00,3,2017-12-27 14:06:00,9969694820036681168,0 days 00:00:00,2017-12-27 14:06:00

In [24]:
added_first_order_month['order_month'] = added_first_order_month['Start Ts'].dt.to_period('M')
added_first_order_month.head()

,Device,End Ts,Source Id,Start Ts,Uid,session_time,first_visit_date,order_month
0,touch,2017-12-20 17:38:00,4,2017-12-20 17:20:00,16879256277535980062,0 days 00:18:00,2017-12-20 17:20:00,2017-12
1,desktop,2018-02-19 17:21:00,2,2018-02-19 16:53:00,104060357244891740,0 days 00:28:00,2018-02-19 16:53:00,2018-02
2,touch,2017-07-01 01:54:00,5,2017-07-01 01:54:00,7459035603376831527,0 days 00:00:00,2017-07-01 01:54:00,2017-07
3,desktop,2018-05-20 11:23:00,9,2018-05-20 10:59:00,16174680259334210214,0 days 00:24:00,2018-03-09 20:05:00,2018-05
4,desktop,2017-12-27 14:06:00,3,2017-12-27 14:06:00,9969694820036681168,0 days 00:00:00,2017-12-27 14:06:00,2017-12

In [25]:
added_first_order_month['first_visit_date'] = added_first_order_month['first_visit_date'].dt.to_period('M')
added_first_order_month.head()

,Device,End Ts,Source Id,Start Ts,Uid,session_time,first_visit_date,order_month
0,touch,2017-12-20 17:38:00,4,2017-12-20 17:20:00,16879256277535980062,0 days 00:18:00,2017-12,2017-12
1,desktop,2018-02-19 17:21:00,2,2018-02-19 16:53:00,104060357244891740,0 days 00:28:00,2018-02,2018-02
2,touch,2017-07-01 01:54:00,5,2017-07-01 01:54:00,7459035603376831527,0 days 00:00:00,2017-07,2017-07
3,desktop,2018-05-20 11:23:00,9,2018-05-20 10:59:00,16174680259334210214,0 days 00:24:00,2018-03,2018-05
4,desktop,2017-12-27 14:06:00,3,2017-12-27 14:06:00,9969694820036681168,0 days 00:00:00,2017-12,2017-12

In [28]:
#Obtenemos la cantidad absoluta de usuarios que vuelven a visitar el sitio en periodos mensuales.
absolute_visits = added_first_order_month.pivot_table(
    index = 'first_visit_date',
    columns= 'order_month',
    values = 'Uid',
    aggfunc = 'nunique'
)
absolute_visits

order_month,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05
first_visit_date,,,,,,,,,,,,
2017-06,13259.0,1043.0,713.0,814.0,909.0,947.0,809.0,766.0,694.0,674.0,539.0,596.0
2017-07,NaN,13140.0,737.0,674.0,738.0,765.0,633.0,596.0,601.0,510.0,376.0,361.0
2017-08,NaN,NaN,10181.0,783.0,640.0,639.0,510.0,448.0,370.0,402.0,284.0,265.0
2017-09,NaN,NaN,NaN,16704.0,1428.0,1156.0,847.0,658.0,632.0,599.0,404.0,381.0
2017-10,NaN,NaN,NaN,NaN,25977.0,2042.0,1357.0,1012.0,890.0,837.0,555.0,529.0
2017-11,NaN,NaN,NaN,NaN,NaN,27248.0,2133.0,1202.0,1054.0,919.0,638.0,594.0
2017-12,NaN,NaN,NaN,NaN,NaN,NaN,25268.0,1410.0,960.0,786.0,512.0,481.0
2018-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22624.0,1351.0,890.0,565.0,458.0
2018-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22197.0,1267.0,565.0,446.0
2018-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20589.0,861.0,557.0
2018-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15709.0,760.0
2018-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15273.0

In [79]:
#Agrupamos los periodos y los meses de la primera visita de los usuarios
porcent_visits = added_first_order_month.groupby(['first_visit_date', 'order_month']).agg({'Uid':'nunique'}).reset_index()
porcent_visits.columns = ['first_visit_date', 'order_month', 'cohort_users']
porcent_visits.head()

  first_visit_date order_month  cohort_users
0          2017-06     2017-06         13259
1          2017-06     2017-07          1043
2          2017-06     2017-08           713
3          2017-06     2017-09           814
4          2017-06     2017-10           909

In [80]:
#Obtendremos la cantidad de usuarios que hacen su primera visita en cada mes
first_month_users = added_first_order_month.groupby('first_visit_date')['Uid'].nunique().reset_index()
first_month_users.columns = ['first_visit_date', 'first_cohort_users']
first_month_users.head()

  first_visit_date  first_cohort_users
0          2017-06               13259
1          2017-07               13140
2          2017-08               10181
3          2017-09               16704
4          2017-10               25977

  first_visit_date  first_cohort_users
0          2017-06               13259
1          2017-07               13140
2          2017-08               10181
3          2017-09               16704
4          2017-10               25977